/** @type {import('tailwindcss').Config} */
export default {
    content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
    theme: {
        extend: {},
    },
    daisyui: {
        themes: [
            'light',
            'dark',
            'cupcake',
            'cyberpunk',
            'halloween',
            'light',
            'luxury',
            'material',
            'mint',
            'retro',
            'synthwave',
            'valentine',
            'vaporwave',
            'business',
            'casual',
            'dracula',
            'dream',
            'fantasy',
            'forest',
            'formal',
            'garden',
            'hipster',
            'holiday',
            'icy',
            'jungle',
            'luxury',
            'pastel',
            'retro',
            'synthwave',
            'valentine',
            'vaporwave',
            'business',
            'casual',
            'dark',
            'dracula',
            'edge',
            'aqua',
        ],
    },
    plugins: [require('daisyui')],
}
